# ============================================================
# Ingest a user's real dataset for GAN training.
#
# Input follows the SCENIC / PFAS_SIM convention: features x samples
# matrices for the exposure and outcome panels, an optional
# negative-control panel, and a sample-level covariate data frame.
# The heavy lifting is turning that into a tidy sample x variable
# frame the generator can learn from, plus keeping the raw matrices
# for calibration downstream.
#
# In addition to the sample-level training frame, the function now
# computes feature-level residual correlation matrices for each
# available panel (Y, M, W).  These capture the cross-feature
# correlation structure that persists after removing the sample-level
# signal (exposure level + covariates), so that the simulation can
# inject realistic correlated noise into the mediator and negative-
# control panels rather than independent noise.
# ============================================================

# Tokens the estimators reserve when they paste covariate names into
# model formulas (see .covar_str in estimators.R). Covariates that
# collide with these would silently corrupt a regression, so we rename.
.reserved_covar_tokens <- c("y", "Z", "g", "w", "W_hat", "G_inst", "Z_resid", "Zc")

#' Load and standardise a real multi-omic dataset for GAN training
#'
#' Accepts the exposure, outcome, mediator (optional), and negative-control
#' panels as `features x samples` matrices together with a sample-level
#' covariate frame, and returns the tidy structures used by
#' [train_gan_on_real_data()] and the calibration step of
#' [run_single_iteration()].
#'
#' In addition to the sample-level training frame (one row per sample with
#' exposure level, outcome level, and encoded covariates), the function
#' computes feature-level residual correlation matrices for each available
#' panel (Y, M, W).  These capture the cross-feature correlation structure
#' that remains after removing the sample-level signal, so the simulation
#' can inject realistic correlated noise into the mediator and negative-
#' control panels.
#'
#' If no matrices are supplied a small built-in example dataset is returned,
#' so the pipeline can be exercised end-to-end without real data.
#'
#' @param Z_matrix       Exposure panel, `features x samples` (e.g. maternal
#'   PFAS z-scores across probes). Column means become the per-sample exposure.
#' @param Y_matrix       Outcome, either a scalar vector of length `n_samples`
#'   (e.g. birth weight) or a `features x samples` matrix. When a vector, it
#'   defines `n_samples`; when a matrix, `n_samples` and `n_features`.
#' @param M_matrix       Mediator panel, `features x samples` (e.g. placental
#'   transcript expression). When supplied, its per-sample summary is added to
#'   the GAN training frame (so the generator learns the mediator's marginal
#'   distribution) and its residual correlation matrix is computed and stored.
#' @param W_matrix       Optional negative-control panel, `features x samples`.
#'   When supplied the controls are treated as user-provided real structure;
#'   when `NULL` they are generated by a negative-control model at simulation time.
#' @param covariates_df  Optional data frame of sample-level covariates. A
#'   `sample_id` column is used to align samples if present; recognised columns
#'   `sex`, `GA`, `mother_ethnicity` are encoded, and any other numeric columns
#'   are z-scored and kept. Names colliding with estimator-reserved tokens are
#'   renamed with a `cov_` prefix.
#' @param example        Force return of the built-in example dataset. Default
#'   `FALSE` (auto-enabled when no matrices are given).
#' @param marginal_method Marginal fitting method for the feature-level copula
#'   texture model (mediator panel): \code{"auto"} (default, uses parametric
#'   if KS test passes at p > 0.05, otherwise empirical), \code{"empirical"}
#'   (always empirical CDF), or \code{"parametric"} (always best parametric
#'   fit by AIC).  See [train_feature_texture()].
#' @param residualize_on Character (v0.9.2, JYH #1109): \code{"ZC"} (default)
#'   residualizes the Y/W correlation on exposure + covariates only;
#'   \code{"ZCW"} additionally residualizes on the W bridge proxy (PC1 of W),
#'   reducing U-signature double-counting. Recommended only when the
#'   completeness-capture test reports "strong".
#'
#' @return A list with `gan_training_data` (sample x variable data frame with
#'   exposure level, outcome level, mediator level, and encoded covariates),
#'   `original_matrices` (`Z`, `Y`, `M`, `W`), `covariates` (encoded frame),
#'   `feature_correlations` (list with `Y`, `W` residual correlation matrices,
#'   or `NULL` for absent panels), `feature_texture` (an
#'   `iconic_feature_texture` object for the mediator panel, or `NULL` when
#'   no M matrix is supplied), `sample_names`, `feature_names`, `n_samples`,
#'   `n_features`.
#' @export
load_real_input_data <- function(Z_matrix     = NULL,
                                 Y_matrix      = NULL,
                                 M_matrix      = NULL,
                                 W_matrix      = NULL,
                                 covariates_df = NULL,
                                 example       = FALSE,
                                 marginal_method = "auto",
                                 residualize_on = c("ZC", "ZCW")) {

  if (is.null(Z_matrix) && is.null(Y_matrix) && is.null(covariates_df))
    example <- TRUE

  if (example) {
    ex            <- .make_example_input()
    Z_matrix      <- ex$Z_matrix
    Y_matrix      <- ex$Y_matrix
    M_matrix      <- ex$M_matrix
    W_matrix      <- ex$W_matrix
    covariates_df <- ex$covariates_df
  }

  if (is.null(Y_matrix)) stop("Y_matrix (outcome) is required.")
  Y_matrix <- as.matrix(Y_matrix)
  if (is.null(Z_matrix)) stop("Z_matrix (exposure panel) is required.")
  Z_matrix <- as.matrix(Z_matrix)

  # Y can be a scalar vector (1 x n) or a features x samples matrix.
  # When scalar (e.g. birth weight), n_features is determined by M or W.
  if (nrow(Y_matrix) == 1) {
    n_samples  <- ncol(Y_matrix)
    n_features <- if (!is.null(M_matrix)) nrow(as.matrix(M_matrix))
                  else if (!is.null(W_matrix)) nrow(as.matrix(W_matrix))
                  else 20L
  } else {
    n_samples  <- ncol(Y_matrix)
    n_features <- nrow(Y_matrix)
  }

  if (ncol(Z_matrix) != n_samples)
    stop("Z_matrix and Y_matrix must have the same number of samples (columns).")
  if (!is.null(M_matrix)) {
    M_matrix <- as.matrix(M_matrix)
    if (ncol(M_matrix) != n_samples)
      stop("M_matrix must have the same number of samples (columns) as Y_matrix.")
  }
  if (!is.null(W_matrix)) {
    W_matrix <- as.matrix(W_matrix)
    if (ncol(W_matrix) != n_samples)
      stop("W_matrix must have the same number of samples (columns) as Y_matrix.")
  }

  sample_names  <- colnames(Y_matrix)
  if (is.null(sample_names)) sample_names <- paste0("sample_", seq_len(n_samples))
  feature_names <- rownames(Y_matrix)
  if (is.null(feature_names)) feature_names <- paste0("feature_", seq_len(n_features))

  covars <- .encode_covariates(covariates_df, n_samples, sample_names)

  # Per-sample summaries (mean across features), standardised. This is the
  # tabular signal the generator learns: exposure level, outcome level,
  # mediator level, and the encoded covariates, jointly, one row per sample.
  pfas_z <- as.numeric(scale(colMeans(Z_matrix, na.rm = TRUE)))

  # Y: scalar outcome (e.g. birth weight) — one value per sample.
  # When Y_matrix is 1 x n, take the single row; otherwise column means.
  outcome_vec <- if (nrow(Y_matrix) == 1) as.numeric(Y_matrix[1, ])
                  else as.numeric(scale(colMeans(Y_matrix, na.rm = TRUE)))
  outcome_vec <- as.numeric(scale(outcome_vec))

  # M: mediator panel (e.g. placental transcript expression) — per-sample
  # mean added to the GAN training frame so the generator learns the
  # mediator's marginal distribution, not just its correlation structure.
  mediator_vec <- if (!is.null(M_matrix))
                    as.numeric(scale(colMeans(as.matrix(M_matrix), na.rm = TRUE)))
                  else NULL

  gan_training_data <- data.frame(exposure_level  = pfas_z,
                                  outcome_level   = outcome_vec)
  if (!is.null(mediator_vec))
    gan_training_data$mediator_level <- mediator_vec
  if (ncol(covars)) gan_training_data <- cbind(gan_training_data, covars)

  # ── Feature-level texture models ──
  # Residual correlation matrices for Y and W panels (used by
  # run_single_iteration() to inject correlated noise into the outcome and
  # negative-control equations).  The mediator (M) panel is modelled by a
  # Gaussian copula with flexible marginals (train_feature_texture()), which
  # captures both the marginal shapes and the cross-feature dependence —
  # replacing the residual-correlation-only approach for M.
  # v0.9.2 (JYH #1109): when residualize_on = "ZCW", the Y residual
  # correlation additionally partials out the W bridge proxy Ŵ, reducing
  # the double-counting of U's cross-feature signature.
  feature_correlations <- list(
    Y = if (nrow(Y_matrix) > 1)
          .residual_correlation(Y_matrix, pfas_z, covars,
                                residualize_on = residualize_on,
                                W_mat = W_matrix)
        else NULL,
    W = if (!is.null(W_matrix))
          .residual_correlation(W_matrix, pfas_z, covars)
        else NULL
  )

  # Feature-level copula texture model for the mediator panel.
  feature_texture <- if (!is.null(M_matrix))
                       train_feature_texture(M_matrix, marginal_method = marginal_method)
                     else NULL

  list(
    gan_training_data    = gan_training_data,
    original_matrices    = list(Z = Z_matrix, Y = Y_matrix, M = M_matrix, W = W_matrix),
    covariates           = covars,
    feature_correlations = feature_correlations,
    feature_texture      = feature_texture,
    sample_names         = sample_names,
    feature_names        = feature_names,
    n_samples            = n_samples,
    n_features           = n_features
  )
}


#' Compute the residual correlation matrix of a features x samples panel (internal)
#'
#' Residualizes each feature (row) on the sample-level exposure and covariates,
#' then computes the p x p correlation matrix of the residuals.  Returns NULL
#' if the matrix has fewer than 2 features or the correlation is degenerate.
#'
#' @param mat   A `features x samples` numeric matrix.
#' @param exposure  A length-n_samples numeric vector (per-sample exposure).
#' @param covars    A data frame of encoded covariates (n_samples rows).
#' @param residualize_on Character: `"ZC"` (default, legacy) residualizes on
#'   exposure + covariates only; `"ZCW"` (v0.9.2, JYH #1109) additionally
#'   residualizes on the negative-control bridge proxy Ŵ, obtained by
#'   regressing `W_mat` on exposure + covariates. This partials out the
#'   U-signature that W captures, reducing the double-counting of U's
#'   cross-feature signature when the residual matrix is later injected as
#'   correlated noise alongside synthetic U loadings. Tradeoff: can
#'   over-partial if W is a weak proxy — recommended only when the
#'   completeness-capture test (§1) reports "strong".
#' @param W_mat  Optional `features x samples` NC matrix used to construct
#'   the bridge proxy Ŵ when `residualize_on = "ZCW"`. Ignored otherwise.
#' @return A p x p correlation matrix, or NULL.
#' @keywords internal
.residual_correlation <- function(mat, exposure, covars,
                                  residualize_on = c("ZC", "ZCW"),
                                  W_mat = NULL) {
  residualize_on <- match.arg(residualize_on)
  if (is.null(mat)) return(NULL)
  mat <- as.matrix(mat)
  p <- nrow(mat)
  n <- ncol(mat)
  if (p < 2 || n < 5) return(NULL)

  # v0.9.2 (JYH #1109): build the bridge proxy Ŵ from the W panel.
  # W captures U; residualizing Y on W's U-direction partials out the
  # U-signature that Z alone misses, reducing double-counting. We use the
  # PC1 of the raw W panel (the dominant U-capturing direction). We do NOT
  # residualize W on Z + C first, because Z already proxies U and would
  # strip W's U-signal — defeating the purpose. The bridge is then
  # included alongside Z + C in the Y residualization, so any U-variance
  # W captures beyond what Z + C explain is partialled out.
  # Only active when W_mat is supplied and residualize_on = "ZCW".
  bridge <- NULL
  if (residualize_on == "ZCW" && !is.null(W_mat)) {
    Wm <- as.matrix(W_mat)
    if (nrow(Wm) >= 2 && ncol(Wm) == n) {
      Wc <- t(Wm)  # n x p
      Wc[is.na(Wc)] <- 0
      # PC1 of the W panel = dominant U-capturing direction
      sv <- svd(Wc, nu = 1, nv = 0)
      bridge <- as.numeric(scale(sv$u[, 1]))
    }
  }

  # Residualize each feature on exposure + covariates (+ bridge when ZCW)
  resid_mat <- matrix(NA_real_, p, n)
  for (f in seq_len(p)) {
    y <- as.numeric(mat[f, ])
    d <- data.frame(y = y, exposure = exposure)
    if (!is.null(bridge)) d$bridge <- bridge
    if (!is.null(covars) && ncol(covars) > 0)
      d <- cbind(d, covars)
    fit <- tryCatch(
      lm(y ~ ., data = d),
      error = function(e) NULL
    )
    resid_mat[f, ] <- if (!is.null(fit)) as.numeric(residuals(fit)) else y
  }

  # Correlation matrix of the residuals
  cor_mat <- tryCatch(
    cor(t(resid_mat), use = "pairwise.complete.obs"),
    error = function(e) NULL
  )
  if (is.null(cor_mat)) return(NULL)

  # Ensure it's a valid correlation matrix: symmetric, positive-definite
  cor_mat[is.na(cor_mat)] <- 0
  diag(cor_mat) <- 1
  # Near-PD correction via eigenvalue clipping
  eig <- eigen(cor_mat, symmetric = TRUE)
  eig_vals <- pmax(eig$values, 1e-6)
  cor_mat <- eig$vectors %*% diag(eig_vals) %*% t(eig$vectors)
  # Re-normalize to unit diagonal
  dd <- sqrt(diag(cor_mat))
  cor_mat <- cor_mat / outer(dd, dd)
  diag(cor_mat) <- 1

  cor_mat
}


#' Encode a covariate data frame into a numeric model matrix (internal)
#'
#' Binary-encodes `sex`, z-scores `GA` and any other numeric column, one-hot
#' encodes `mother_ethnicity`, drops `sample_id`, and renames any column whose
#' name collides with an estimator-reserved token.
#' @keywords internal
.encode_covariates <- function(covariates_df, n_samples, sample_names) {
  if (is.null(covariates_df) || !ncol(as.data.frame(covariates_df)))
    return(data.frame(row.names = seq_len(n_samples))[, 0, drop = FALSE])

  df <- as.data.frame(covariates_df, stringsAsFactors = FALSE)
  df$sample_id <- NULL

  # Dimension check: covariates must have one row per sample. A transposed
  # input (n_samples columns x p rows) is a common mistake; catch it here
  # with a clear message instead of letting lm() fail downstream.
  if (nrow(df) != n_samples) {
    stop("covariates has ", nrow(df), " rows but the data has ", n_samples,
         " samples. covariates must be a data frame with one row per sample",
         " (n rows x p columns). If your covariates are stored transposed",
         " (p x n), wrap them in as.data.frame(t(...)) before passing",
         " to iconic_data().")
  }

  out <- list()
  for (nm in names(df)) {
    col <- df[[nm]]
    if (nm == "sex") {
      out[["sex"]] <- as.numeric(tolower(as.character(col)) %in% c("male", "m", "1"))
    } else if (nm == "mother_ethnicity" || is.character(col) || is.factor(col)) {
      lv <- sort(unique(as.character(col)))
      lv <- lv[-1]                       # drop first level as reference
      for (l in lv)
        out[[paste0(make.names(nm), "_", make.names(l))]] <-
          as.numeric(as.character(col) == l)
    } else {
      out[[nm]] <- as.numeric(scale(as.numeric(col)))
    }
  }

  enc <- if (length(out)) as.data.frame(out, stringsAsFactors = FALSE)
         else data.frame(row.names = seq_len(n_samples))[, 0, drop = FALSE]

  # Guard against collisions with estimator-reserved formula tokens.
  clash <- names(enc) %in% .reserved_covar_tokens
  if (any(clash)) names(enc)[clash] <- paste0("cov_", names(enc)[clash])
  names(enc) <- make.names(names(enc), unique = TRUE)
  enc
}


#' Build a small synthetic example input dataset (internal)
#'
#' Produces `features x samples` Z/M/W matrices, a scalar outcome vector Y
#' (birth weight), and a covariate frame with the recognised
#' `sample_id`/`sex`/`GA`/`mother_ethnicity` columns, so the pipeline runs
#' without user data. Not a benchmark DGP; just plumbing exercise data.
#' @keywords internal
.make_example_input <- function(n_samples = 200, n_features = 30, seed = 1) {
  set.seed(seed)
  U  <- rnorm(n_samples)                                   # shared confounder
  sex <- rbinom(n_samples, 1, 0.5)
  GA  <- rnorm(n_samples, 39, 1.5)
  eth <- sample(c("chinese", "indian", "malay"), n_samples, replace = TRUE)

  # v0.8.2: block-diagonal co-expression modules (within-block r = 0.5)
  # so that .residual_correlation() has genuine cross-feature structure
  # to learn, not just the shared confounder (which gets residualized away).
  block_cor <- .block_diag_cor(n_features, 0.5)

  Zm <- matrix(rnorm(n_features * n_samples), n_features, n_samples) +
        matrix(rep(0.8 * U, each = n_features), n_features, n_samples)
  # Y: scalar outcome (birth weight) — confounder + sex + noise
  Ym <- matrix(3000 + 200 * U + 100 * sex + rnorm(n_samples, 0, 300),
               nrow = 1, ncol = n_samples)
  # Mediator panel: shared confounder + co-expression module noise
  M_noise <- if (!is.null(block_cor))
      MASS::mvrnorm(n_samples, rep(0, n_features), block_cor * 0.5^2) else
      matrix(rnorm(n_features * n_samples), n_samples, n_features)
  Mm <- t(M_noise + matrix(rep(0.5 * U, n_features),
                           n_samples, n_features, byrow = FALSE))
  # Negative-control panel: shared confounder + co-expression module noise
  W_noise <- if (!is.null(block_cor))
      MASS::mvrnorm(n_samples, rep(0, n_features), block_cor * 0.5^2) else
      matrix(rnorm(n_features * n_samples), n_samples, n_features)
  Wm <- t(W_noise + matrix(rep(0.7 * U, n_features),
                           n_samples, n_features, byrow = FALSE))

  colnames(Zm) <- colnames(Ym) <- colnames(Mm) <- colnames(Wm) <- paste0("S", seq_len(n_samples))
  rownames(Ym) <- "birth_weight"
  rownames(Mm) <- paste0("transcript", seq_len(n_features))
  rownames(Zm) <- paste0("pfas", seq_len(n_features))
  rownames(Wm) <- paste0("nc",   seq_len(n_features))

  list(
    Z_matrix = Zm, Y_matrix = Ym, M_matrix = Mm, W_matrix = Wm,
    covariates_df = data.frame(
      sample_id        = paste0("S", seq_len(n_samples)),
      sex              = ifelse(sex == 1, "Male", "Female"),
      GA               = GA,
      mother_ethnicity = eth,
      stringsAsFactors = FALSE
    )
  )
}
